### PR TITLE
dedicated project for generator dependencies

### PR DESCRIPTION
**Pull request by LorenzoBettini**
This is another (the 3rd) alternative possible solution for eclipse/xtext#1976

The idea is that we (Xtext) provide an additional Maven project that, relying on the BOM, lists all the dependencies that are known to use version ranges so that we know we pin them once and for all (as soon as we update the BOM, everything will automatically be updated).

In this PR, which aims at recreating such a situation, I call such a project `org.eclipse.xtext.generator.dependencies`. In the script I simulate the final user experience by first installing such a project in the local Maven repository. Then, the `exec-maven-plugin` configuration only lists such a dependency.

This is a pure Maven solution, which does not interfere with the TP anyway.

Note that we have to list all the dependencies (including EMF ones) to avoid the version ranges.

I tested it locally and I verified that no additional Eclipse and EMF JARs are downloaded when running `exec-maven-plugin`. (what I've done is start from a clean `.m2` repository, install first this new `org.eclipse.xtext.generator.dependencies` and then build the Tycho example, verifying that no other Eclipse and EMF JAR are downloaded... it wasn't fun ;)

This solution will work without touching the MANIFEST, it only requires the POM of the DSL to be modified.

Note that this solution will give us (Xtext) full control...

OF COURSE, this PR is not meant to be merged, it's just to show a possible solution that will then require to add such a new project to Xtext. With that respect, I seem to understand that our Maven POMs are actually generated by Gradle, aren't they? I guess this should be a problem since the build.gradle still can benefit from our BOM, can't it?

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
By the way, it might be the case that the actual version pinning could (or should) be done at the level of https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.generator/build.gradle 
There we list only the top-level dependencies but the transitive dependency hell is unleashed by `org.eclipse.emf:org.eclipse.emf.codegen.ecore`:

image

**Comment by cdietrich** [comment]
@LorenzoBettini i am quite busy for the rest of the week.
i suppose this module would belong to xtext-core.
i also wonder if we should mingle here instead 
https://github.com/eclipse/xtext-core/compare/cd_xtext_issue1976
maybe even with more sophisticated excludes

**Comment by LorenzoBettini** [comment]
@cdietrich As I said in my second comment, I think we should pin the dependencies in `xtext.xtext.generator` and also in `xtext.common.types`, I'll try to update the PR with such a "simulation" (I'll pin the dependencies in these dependencies project, highlighting where they should go). I think exclusion might be too unsafe and could raise problems in the future, while pinning all the transitive dependencies will not break in case of new artifacts showing up...

**Comment by LorenzoBettini** [comment]
I've updated the dependencies with detailed information about the transitivity... I think this should be used to pin the versions in xtext.xtext.generator and common.types

**Pull request closed without merging**
