### PR TITLE
[https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
Looks like you forgot a lot of places.
Domain model and j11.
E.g.

**Comment by miklossy** [comment]
> Looks like you forgot a lot of places.
> Domain model and j11.
> E.g.

I added these changed to the PR as well.

**Comment by miklossy** [comment]
The failing tests are related to https://github.com/eclipse/xtext-eclipse/pull/1410/files

**Comment by miklossy** [comment]
Still no success. Let's wait some time and try it again later.

**Comment by miklossy** [comment]
Test is green both locally and on Travis:
image

**Comment by miklossy** [comment]
PR Build was successful, but it failed after merge:
image
@cdietrich Do you know what could be the problem?

**Comment by cdietrich** [comment]
travis is bad at caching

**Comment by miklossy** [comment]
Build is green!

**Pull request merged**
