### PR TITLE
Reference projects with Java11

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by szarnekow** [comment]
Sorry @cdietrich , I didn't see your prepared branches :(

**Comment by cdietrich** [comment]
Please ignore them. They were just to test my pr against Xtext

**Comment by szarnekow** [comment]
> Please ignore them. 

That's what I did :)

**Comment by szarnekow** [comment]
Merging, since the build is green. Subsequent review comments will be fixed individually.

**Pull request merged**
